version: '3'

services:

    ####################################################################################################
    # PHP
    ####################################################################################################
    php:
        container_name: qpanel_qrion
        build: .docker/php
        ports:
            - 5173:5173
        volumes:
            - ./:/var/www:cached

    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        container_name: laravel_nginx
        image: nginx
        ports:
            - 8085:80
        volumes:
            - ./:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
